kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
- name: docker  
  image: plugins/docker
  commands:
   - /usr/local/bin/dockerd --data-root /var/lib/docker --host=unix:///var/run/docker.sock
   - docker ps
