FROM alpine as fnm-downloader
RUN apk add --no-cache wget unzip
RUN wget https://github.com/Schniz/fnm/releases/download/v1.31.0/fnm-{% if _arch == 'x64' %}linux{% else %}arm64{% endif %}.zip -O fnm.zip
RUN unzip fnm.zip
RUN chmod +x fnm

FROM {% block image_from %}php:{{ phpVersion }}-cli{% endblock %}

LABEL org.opencontainers.image.source https://github.com/shyim/shopware-docker
ENV XDEBUG_MODE=debug \
    SMTP_ADDRESS=smtp:1025
ENV PS1 '${debian_chroot:+($debian_chroot)}\[\033[01;31m\]\u\[\033[01;33m\]@\[\033[01;36m\]\h \[\033[01;33m\]\w \[\033[01;35m\]\$ \[\033[00m\]'
COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/bin/
COPY --from=ghcr.io/shyim/shopware-docker/sendmail /sendmail /usr/bin/sendmail
COPY --from=composer:1 /usr/bin/composer /usr/bin/composer-native-1
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer-native-2

ENV PHP_DUMP_SERVER_URL=http://dump-server:9009

COPY --from=fnm-downloader /fnm /usr/local/bin

RUN set -x && \
    apt-get update && \
    apt-get install -y --no-install-recommends unzip \
        bash \
        bash-completion \
        wget \
        git \
        zip \
        patch \
        mariadb-client \
        jq \
        make && \
    rm -rf /var/lib/apt/lists/* && \
    install-php-extensions bcmath gd intl mysqli pdo_mysql sockets bz2 gmp soap zip gmp pcntl posix redis pcov imagick xsl calendar{% if phpVersionNumeric >= 74 %} ffi {% endif %} {% if production %} opcache {% endif %} {% if xdebug %} xdebug{% if phpVersionNumeric >= 71 and xdebug == 2 %}-2.9.8{% endif %} {% endif %} && \
    rm -rf /tmp/* && \
    useradd dev && \
    mkdir /home/dev && \
    mkdir -p /opt/phpstorm-coverage && \
    chown -R dev /home/dev /opt/ && \
    cd /tmp && \
    wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_{% if _arch == 'x64' %}amd64{% else %}arm64{% endif %} -O /usr/local/bin/yq && \
    chmod +x /usr/local/bin/yq {% if xdebug %} && \
    {% if xdebug == 2 %}
    echo 'xdebug.remote_enable=1' > /usr/local/etc/php/conf.d/ext-xdebug.ini && \
    echo 'xdebug.remote_autostart=0' >> /usr/local/etc/php/conf.d/ext-xdebug.ini && \
    echo 'xdebug.remote_connect_back=1' >> /usr/local/etc/php/conf.d/ext-xdebug.ini && \
    echo 'xdebug.remote_port=9000' >> /usr/local/etc/php/conf.d/ext-xdebug.ini && \
    echo 'xdebug.remote_log=/tmp/xdebug.log' >> /usr/local/etc/php/conf.d/ext-xdebug.ini && \
    echo 'xdebug.idekey=PHPSTORM' >> /usr/local/etc/php/conf.d/ext-xdebug.ini && \
    echo 'xdebug.profiler_enable=0' >> /usr/local/etc/php/conf.d/ext-xdebug.ini && \
    echo 'xdebug.profiler_enable_trigger=1' >> /usr/local/etc/php/conf.d/ext-xdebug.ini && \
    echo 'xdebug.profiler_output_dir="/tmp/xdebug"' >> /usr/local/etc/php/conf.d/ext-xdebug.ini && \
    echo 'xdebug.profiler_output_name = "cachegrind.out.%R.%t"' >> /usr/local/etc/php/conf.d/ext-xdebug.ini && \
    echo 'xdebug.auto_trace=0' >> /usr/local/etc/php/conf.d/ext-xdebug.ini && \
    echo 'xdebug.trace_enable_trigger=1' >> /usr/local/etc/php/conf.d/ext-xdebug.ini && \
    echo 'xdebug.trace_output_dir="/var/www/html/traces"' >> /usr/local/etc/php/conf.d/ext-xdebug.ini && \
    echo 'xdebug.trace_output_name="trace.%R.%t"' >> /usr/local/etc/php/conf.d/ext-xdebug.ini && \
    echo 'xdebug.show_mem_delta=1' >> /usr/local/etc/php/conf.d/ext-xdebug.ini
    {% else %}
    echo 'xdebug.discover_client_host=true' >> /usr/local/etc/php/conf.d/xdebug.ini && \
    echo 'xdebug.client_port=9000' >> /usr/local/etc/php/conf.d/xdebug.ini && \
    echo 'xdebug.log=/tmp/xdebug.log' >> /usr/local/etc/php/conf.d/xdebug.ini && \
    echo 'xdebug.output_dir="/tmp/xdebug"' >> /usr/local/etc/php/conf.d/xdebug.ini
    {% endif %}
{% endif %}

{% if phpVersionNumeric >= 71 and xdebug == false %}
RUN cd /opt/ && \
    wget https://github.com/shyim/php-dump-client-prefixed/archive/main.zip && \
    unzip main.zip && \
    rm main.zip && \
    mv php-dump-client-prefixed-main php-dump-client-prefixed && \
    echo "auto_prepend_file = /opt/php-dump-client-prefixed/prepend.php" > /usr/local/etc/php/conf.d/vardumpserver.ini
{% endif %}

{% block after_install %}{% endblock %}

ENV HOME /home/dev
USER dev

COPY rootfs/ /

RUN echo "alias ll=\"ls -lha\"" >> ~/.bashrc && \
    echo 'eval $(fnm --fnm-dir=/nvm/.debian-fnm env --shell=bash)' >> ~/.bashrc

WORKDIR /var/www/html

ENTRYPOINT [ "/entrypoint.sh" ]
STOPSIGNAL SIGKILL
